### ISSUE TITLE
IOS issue for Hero image

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/blockstrap#32]
The hero image is not loading on IOS mobile devices in the Safari browser. 

It loads fine for all other devices. 

https://demos.ayecode.io/directory/
![File](https://github.com/user-attachments/assets/2c3280ed-7d4f-464a-b9d1-50b15b943f7b)

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/2701758719/60123?folderId=3812058

**Comment by kprajapatii** [comment]
https://secure.helpscout.net/conversation/2744658501/61945?viewId=3812066#thread-8314011799

**Comment by kprajapatii** [comment]
https://secure.helpscout.net/conversation/2751617173/62278?viewId=3812066#thread-8313307013

**Comment by Stiofan** [comment]
This is an iOS bug, it will be fixed in the release today.
